export enum Path {
  MAIN = '/',
  AUTH = 'auth',
  SIGN_IN = 'sign-in',
  SIGN_UP = 'sign-up',
  SIGN_OUT = 'sign-out',
  SEND_CODE = 'send-code',
  CHECK_CODE = 'check-code',
  CURRENT_USER = 'current-user',
  REFRESH = 'refresh',
  NOT_FOUND = '404',
  USERS = 'users',
  APPEALS = 'appeals',
  PROFILE = 'profile',
}
